version: '3'
services:
  database:
    container_name: postgres-attendance
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - attendance.env  
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data 

  web:
    container_name: nginx-attendance
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - database
    extra_hosts:
      - "app-server:192.168.1.3"

volumes:
  postgres-data:
